# tmux.conf - tmux settings
# Author: Kevin Durbin
# vim: set fdm=marker expandtab ts=2 sw=2:

set -g @plugin_dir "$HOME/.config/tmux/plugins"

# {{{ Theme
set -g @tmux-gruvbox-right-status-z '#h '
run-shell "#{@plugin_dir}/tmux-gruvbox/gruvbox-tpm.tmux"
# }}}

# {{{ Plugins
run-shell "#{@plugin_dir}/tmux-sensible/sensible.tmux"
run-shell "#{@plugin_dir}/tmux-sessionist/sessionist.tmux"
run-shell "#{@plugin_dir}/tmux-pain-control/pain_control.tmux"
run-shell "#{@plugin_dir}/tmux-nerd-font-window-name/tmux-nerd-font-window-name.tmux"
# }}}

# {{{ Navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
# }}}

# {{{ Sesh
bind-key S run-shell "sesh connect $(sesh list -dH | fzf --tmux) || true"
# }}}

# {{{ Settings
run-shell "tmux set-option -g default-shell $(command -v fish)"

set -g allow-rename on    # let programs rename windows
set -g renumber-windows on # keep the windows numbered sanely
set -g base-index 1        # set windows to start at 1
setw -g pane-base-index 1  # set panes to start as 1
set -g main-pane-width 75%
set -g clock-mode-style 12

unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g mouse on
set -g set-clipboard on
setw -g mode-keys vi

set -g set-titles on
set -g set-titles-string '#W'

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB:usstyle"

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
set -g clock-mode-style 12

set -g status-position bottom
set -g status-interval 5

set -g detach-on-destroy off

set -sg escape-time 10
set -g focus-events on

# Resetup the clock after sessionist rebinds it
bind t clock-mode
# }}}

# {{{ Lazygit
bind-key l display-popup -w 80% -h 80% -E lazygit
# }}}
