# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

includes:
  homebrew:
    taskfile: ./.config/taskfiles/homebrew
    aliases: [brew, b]

dotenv: [.env]

tasks:
  default: task --list-all
