# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

tasks:
  commit:
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      DIFF:
        sh: git --no-pager diff -p HEAD
      MSG:
        sh: >
          ollama run --hidethinking gpt-oss:120b-cloud
          "Output ONLY a well formed git conventional commit message for the following diff
          {{.DIFF | shellQuote}}"
    cmd: >
      git commit -am "{{.MSG | trim}}"
