[package]
disabled=true

[nodejs]
disabled=true

[ruby]
disabled=true

[cmd_duration]
format=""

[hostname]
ssh_only=false

[php]
disabled=true

[username]
show_always=true

[directory.substitutions]
"~/projects" = "🚧"
"~" = "🏠"
