# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

tasks:
  bootstrap:macos: >
    sudo nix
    --extra-experimental-features nix-command
    --extra-experimental-features flakes
    run nix-darwin -- switch --flake ~/.config/nix
  update: nix flake update --flake ~/.config/nix
  switch:
    cmd:
      task: 'switch:{{if eq OS "darwin"}}macos{{else}}linux{{end}}'
  switch:macos: sudo darwin-rebuild switch --flake ~/.config/nix
  switch:linux: home-manager switch --flake ~/.config/nix
