require('kevindurb.filetype')
require('kevindurb.general')
require('kevindurb.ripgrep')
require('plugins')
-- require('kevindurb.deps').setup()
-- require('kevindurb.snippets').setup()
-- require('kevindurb.appearance').setup()
-- require('kevindurb.format').setup()
-- require('kevindurb.lint').setup()
-- require('kevindurb.lsp').setup()
-- require('kevindurb.treesitter').setup()
-- require('kevindurb.pairs').setup()
-- require('kevindurb.oil').setup()
-- require('kevindurb.dap').setup()
-- require('kevindurb.surround').setup()
-- require('kevindurb.keymaps').setup()
