default:
  @just -l

use-node version:
  brew unlink node
  brew install node@{{version}}
  brew postinstall node@{{version}}
  brew link --overwrite node@{{version}}

brew-bundle *args:
  brew bundle --global {{args}}

brew-bundle-cleanup:
  @just -g brew-bundle cleanup

brew-bundle-cleanup-force:
  @just -g brew-bundle cleanup --force
