default:
  @just -l

setup:
  mise install
  ya pkg install
  just -g brew-bundle install
  fish -c "fisher update"

upgrade:
  mise upgrade
  ya pkg upgrade
  brew update
  brew upgrade
  fish -c "fisher update"

use-node version:
  brew unlink node
  brew install node@{{version}}
  brew postinstall node@{{version}}
  brew link --overwrite node@{{version}}

brew-bundle *args:
  brew bundle --global {{args}}

brew-bundle-cleanup:
  @just -g brew-bundle cleanup

brew-bundle-cleanup-force:
  @just -g brew-bundle cleanup --force
