# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

tasks:
  status:
    dir: .dotfiles/
    cmd: git status
  pull:
    dir: .dotfiles/
    cmd: git pull
  push:
    dir: .dotfiles/
    cmd: git push
  sync:
    dir: .dotfiles/
    cmd: git sync
