font_size 12.0
font_family JetBrainsMono Nerd Font
modify_font cell_height +2px

enable_audio_bell no
allow_remote_control socket-only
listen_on unix:/tmp/kitty
macos_option_as_alt yes


# BEGIN_KITTY_THEME
# Catppuccin-Latte
include current-theme.conf
# END_KITTY_THEME
