#! /bin/bash

DIRS=(
  ctags
  gh
  git
  kitty
  mycli
  nvim
  prettier
  ssh
  starship
  tmate
  tmux
  zsh
)

for DIR in "${DIRS[@]}"; do
  echo "linking $DIR"
  stow -d ~/.dotfiles -t ~ "$DIR"
done
