FROM docker.io/library/fedora:37

ARG TARGETARCH
ARG NVM_VERSION="v0.39.2"

COPY ./ci/files/kubernetes.$TARGETARCH.repo /etc/yum.repos.d/kubernetes.repo

RUN dnf update -y && \
  dnf install -y \
  ansible \
  autojump-zsh \
  bat \
  bc \
  curl \
  diffutils \
  entr \
  exa \
  findutils \
  fzf \
  gcc \
  gcc-c++ \
  gh \
  git \
  git-delta \
  httpie \
  jq \
  just \
  kubectl \
  less \
  litecli \
  make \
  man \
  mycli \
  ncdu \
  ncurses \
  neofetch \
  neovim \
  openssl \
  passwd \
  pgcli \
  pinentry \
  prettyping \
  procps-ng \
  python-pip \
  rcm \
  ripgrep \
  shadow-utils \
  tig \
  tldr \
  tmux \
  util-linux \
  util-linux-user \
  vte-profile \
  wget \
  zsh && \
  dnf clean all

# install neovim dependency
RUN pip install neovim

# Install starship prompt
RUN wget -O /tmp/install_starship.sh https://starship.rs/install.sh
RUN sh /tmp/install_starship.sh --yes

# Setup kevindurb user
RUN useradd -s /usr/bin/zsh -m kevindurb
USER kevindurb

# Install antigen
RUN curl -L git.io/antigen > /home/kevindurb/antigen.zsh

# Install nvm
ENV NVM_DIR=/home/kevindurb/.nvm
RUN mkdir -p "${NVM_DIR}"
RUN wget -O /tmp/install_nvm.sh "https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh"
RUN bash /tmp/install_nvm.sh
RUN source "${NVM_DIR}/nvm.sh" && nvm install lts/*

# install neovim dependency
RUN source "${NVM_DIR}/nvm.sh" && npm install -g \
  neovim

# Copy over dotfiles
COPY --chown=kevindurb:kevindurb ./ /home/kevindurb/.dotfiles
WORKDIR /home/kevindurb/.dotfiles
RUN just

WORKDIR /home/kevindurb/
ENV SHELL=/usr/bin/zsh
ENTRYPOINT ["/usr/bin/zsh"]
