FROM registry.fedoraproject.org/fedora-toolbox:37

ARG TARGETARCH
ARG NVM_VERSION="v0.39.2"

COPY ./ci/files/kubernetes.$TARGETARCH.repo /etc/yum.repos.d/kubernetes.repo

RUN dnf update -y

RUN dnf install -y \
  ansible \
  autojump-zsh \
  bat \
  bc \
  curl \
  diffutils \
  entr \
  exa \
  findutils \
  fzf \
  gh \
  git \
  httpie \
  jq \
  just \
  kubectl \
  less \
  litecli \
  make \
  mycli \
  ncdu \
  ncurses \
  neofetch \
  neovim \
  openssl \
  passwd \
  pgcli \
  pinentry \
  prettyping \
  procps-ng \
  python-pip \
  rcm \
  ripgrep \
  shadow-utils \
  tig \
  tldr \
  tmux \
  util-linux \
  util-linux-user \
  vte-profile \
  wget \
  zsh

RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/minikube
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/distrobox
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open

RUN pip install neovim

# Install starship prompt
RUN wget -O /tmp/install_starship.sh https://starship.rs/install.sh
RUN sh /tmp/install_starship.sh --yes

# Install nvm
ENV NVM_DIR=/opt/nvm
RUN mkdir -p "${NVM_DIR}"
RUN wget -O /tmp/install_nvm.sh "https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh"
RUN bash /tmp/install_nvm.sh
RUN source "${NVM_DIR}/nvm.sh" && nvm install lts/*

# coc.vim language servers
RUN source "${NVM_DIR}/nvm.sh" && npm install -g \
  dockerfile-language-server-nodejs \
  bash-language-server \
  neovim

RUN chmod -R a+rw /opt/nvm

# Preinstall host-spawn
COPY ./ci/files/host-spawn-$TARGETARCH /usr/bin/host-spawn

ENV SHELL=/usr/bin/zsh

ENTRYPOINT ["/bin/zsh"]
