FROM docker.io/library/fedora:37
#
# ARG TARGETARCH
# ARG NVM_VERSION="v0.39.2"
#
# COPY ./ci/files/kubernetes.$TARGETARCH.repo /etc/yum.repos.d/kubernetes.repo

RUN dnf update -y && \
  dnf install -y \
  openssl \
  passwd \
  ncurses \
  less \
  shadow-utils \
  util-linux \
  util-linux-user \
  vte-profile \
  zsh && \
  dnf clean all
  # ansible \
  # autojump-zsh \
  # bat \
  # bc \
  # curl \
  # diffutils \
  # entr \
  # eza \
  # findutils \
  # fzf \
  # gcc \
  # gcc-c++ \
  # gh \
  # git \
  # git-delta \
  # httpie \
  # jq \
  # just \
  # kubectl \
  # litecli \
  # make \
  # man \
  # mycli \
  # ncdu \
  # neofetch \
  # neovim \
  # pgcli \
  # pinentry \
  # prettyping \
  # procps-ng \
  # python-pip \
  # rcm \
  # ripgrep \
  # tig \
  # tldr \
  # tmux \
  # wget \
  # which \

# install neovim dependency
# RUN pip install neovim

# Install starship prompt
# RUN wget -O /tmp/install_starship.sh https://starship.rs/install.sh
# RUN sh /tmp/install_starship.sh --yes

# Install git-credential-manager
# RUN wget -O /tmp/install_gcm.sh "https://aka.ms/gcm/linux-install-source.sh"
# RUN sh /tmp/install_gcm.sh -y

COPY ./ci/files/sudo_group /etc/sudoers.d/

# Setup kevindurb user
RUN useradd -s /usr/bin/zsh -c Kevin -m kevindurb
USER kevindurb
# ENV GCM_CREDENTIAL_STORE=cache
# RUN git-credential-manager configure

# Install antigen
# RUN curl -L git.io/antigen > /home/kevindurb/antigen.zsh

# Install nvm
# ENV NVM_DIR=/home/kevindurb/.nvm
# RUN mkdir -p "${NVM_DIR}"
# RUN wget -O /tmp/install_nvm.sh "https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh"
# RUN bash /tmp/install_nvm.sh
# RUN source "${NVM_DIR}/nvm.sh" && nvm install lts/*

# install neovim dependency
# RUN source "${NVM_DIR}/nvm.sh" && npm install -g \
#   neovim

# Copy over dotfiles
# COPY --chown=kevindurb:kevindurb ./ /home/kevindurb/.dotfiles
# WORKDIR /home/kevindurb/.dotfiles
# RUN source "${NVM_DIR}/nvm.sh" && just

# WORKDIR /home/kevindurb/
