---
# vim: set ft=yaml.ansible:
- name: Install Packages
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Check if homebrew is available
      block:
        - name: try using homebrew in check_mode (no changes)
          community.general.homebrew:
            update_homebrew: true
          check_mode: true

        - name: Use homebrew packages
          ansible.builtin.set_fact:
            package_list: Homebrew

      rescue:
        - name: Use homebrew packages
          ansible.builtin.set_fact:
            package_list: RedHat

    - name: Gather os specific variables
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - '../vars/{{ package_list }}.yml'

    - name: Add kubernetes repository
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      when: package_list == "RedHat"

    - name: Install packages
      ansible.builtin.package:
        state: present
        name: '{{ host_packages }}'
      tags: packages
      when: package_list != "Homebrew"

    - name: Install packages with homebrew
      community.general.homebrew:
        state: present
        name: '{{ host_packages }}'
      tags: packages
      when: package_list == "Homebrew"

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - neovim
      tags: packages

    - name: Download starship installer
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/install_starship.sh
        mode: 'u+rwx'
      when: package_list == "RedHat"
      register: download_starship
      tags: starship

    - name: Run starship installer
      ansible.builtin.command:
        cmd: /tmp/install_starship.sh --yes
      when: download_starship.changed
      tags: starship

    - name: Download nvm installer
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh'
        dest: /tmp/install_nvm.sh
        mode: 'u+rwx'
      when: package_list == "RedHat"
      register: download_nvm
      tags: nvm

    - name: Run nvm installer
      ansible.builtin.command:
        cmd: /tmp/install_nvm.sh
      when: download_nvm.changed
      tags: nvm

    - name: Ensure latest node lts installed
      ansible.builtin.shell: 'source ~/.nvm/nvm.sh && nvm install {{ node_version }}'
      args:
        executable: /bin/bash
        creates: '~/.nvm/versions/node/{{ node_version }}'
      tags: nvm
