[General]
verbose_logging = True

[Startup]
sync_effects_enabled = True
devices_off_on_screensaver = False
mouse_battery_notifier = True
restore_persistence = True
battery_notifier = False
battery_notifier_freq = 5

[Statistics]
key_statistics = True

