# vim: set ft=tmux fdm=marker expandtab ts=2 sw=2:

set -g @plugin_dir "$HOME/.config/tmux/plugins"

run-shell "#{@plugin_dir}/tmux-sensible/sensible.tmux"
run-shell "#{@plugin_dir}/tmux-sessionist/sessionist.tmux"
run-shell "#{@plugin_dir}/tmux-pain-control/pain_control.tmux"
run-shell "#{@plugin_dir}/tmux-nerd-font-window-name/tmux-nerd-font-window-name.tmux"
